version: "3.9"
services:
  db:
    image: postgres
    container_name: local-pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin001
      POSTGRES_PASSWORD: Admin001234
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgaadmin4
    container_name: pgaadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin001@brujula.com
      PGADMIN_DEFAULT_PASSWORD: Admin001234
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
